---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: splatform/java-buildpack-dependency-builder
    tag: latest

inputs:
- name: java-buildpack-dependency-builder
- name: auto-reconfiguration-archives

run:
  path: java-buildpack-dependency-builder/auto-reconfiguration.sh

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_ENDPOINT:
  CLOUDFRONT_DISTRIBUTION_IDS:
  DOWNLOAD_DOMAIN:
  S3_BUCKET:
