---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfje/java-buildpack-dependency-builder
    tag: latest

inputs:
- name: azure-application-insights-archives
- name: java-buildpack-dependency-builder

run:
  path: java-buildpack-dependency-builder/azure-application-insights.sh

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  CLOUDFRONT_DISTRIBUTION_IDS:
  DOWNLOAD_DOMAIN:
  S3_BUCKET:
