---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/binary_builder_obs_opensuse
inputs:
  - name: java-buildpack-dependency-builder
  - name: source-artifacts
run:
  path: bash
  args:
    - -cl
    - java-buildpack-dependency-builder/ci/tasks/push-sources-to-obs.sh
params:
  RUBYGEM_MIRROR:
