---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: machinerytool/osc_opensuse
inputs:
  - name: ci
  - name: source-artifacts
run:
  path: bash
  args:
    - -cl
    - ci/ci/tasks/push-sources-to-obs.sh
params:
  RUBYGEM_MIRROR:
